api_platform:
  #enable_docs: false
  #enable_entrypoint: false
  show_webby: false
  title: "Vinylothèque"
  description: "Ta Vinylothèque en API"
  version: "2.0.0"
  mapping:
    paths: [ '%kernel.project_dir%/src/Entity' ]
  patch_formats:
    json: [ 'application/merge-patch+json' ]
  swagger:
    versions: [ 3 ]
    api_keys:
      apiKey:
        name: Authorization
        type: header
